### ISSUE TITLE
Create distinct error messages on tag reporting page

### ISSUE THREAD

**Issue by mehallhm** [Cheyenne-Moutain-Computer-Science-Club/spoonSite#20]

**Comment by mehallhm** [comment]
Create unique error messages (possibly modals) for each of the following:

    A user attempts to tag themselves
    A user inputs an invalid/nonexistent ID
    A user who is tagged attempts to tag somebody
    A user attempts to tag somebody who is already tagged

**Comment by hmellow** [comment]
Currently there is absolutely no error handling for invalid IDs. Throws a runtime error.

**Comment by hmellow** [comment]
> Currently there is absolutely no error handling for invalid IDs. Throws a runtime error.

Resolved

**Comment by hmellow** [comment]
Maybe add an array of random error titles and choose randomly from it
